### ISSUE TITLE
What's up guys! It's Quandale Dingle here! I have been arrested for multiple crimes including: Battery on a police officer (WHAT), Grand theft, Declaring war on Italy, and public indecency. I will be escaping prison on, MARCH 28TH! After that.... I WILL T

### ISSUE THREAD

**Issue by chaperiez** [DeoTimeTheGithubUser/BedwarsExtras#1]
What's up guys! It's Quandale Dingle here! (RUUEHEHEHEHEHEEHE) I have been arrested for multiple crimes (AHHHHHHHHHHHHH) including: Battery on a police officer (WHAT), Grand theft, Declaring war on Italy, and public indecency (RUHEHEHEEHEHEHEHEHEHEHE X2 speed). I will be escaping prison on, MARCH 28TH! After that.... I WILL TAKE OVER THE WORLD
Greetings! Quandale Dingle here. My cousin Henry Dinglenut got arrested for putting TNT in a daycare center. (WHAT THE FUCK??) I put a camera in Joe Biden's bathroom and watched him take a poop. (WHAT????) My Asian brother, Quanliling Dingle put illegal substances in my ramen and I died.
Hey, Quandale Dingle here. I just escaped prison and staying at Juandale Pringle's house. As I was running away from cops, I fell and scraped some of my foreskin off. A guy named Garfield Jenson bit me over in the shower while I was in prison. My baby momma Shiniqua Inderson told me to pay child support so I gave my baby to a creepy old guy,
What's up guys, it's Quandele Dingle here
I have been arrested for multiple crimes
Including battery on police officer (what)
Grand theft, declaring war on Italy, and public indecency
I will be escaping prison on March 28th
After that I will take over the world
Greetings, Quandele Dingle here
My cousin Henry Bartholomew Dingle Nut
Got arrested for putting a TNT in a daycare center (what the fuck)
Put a camera on Joe Biden's bathroom and watched him take a poop (what)
My Asian brother Quan Ling Ling Dingle put illegal substances in my ramen and I died
Hey fellas it's Quandele Dingle here
I put perks on Vladimir Putin's drink
And he went to bed for a really long time
I trapped my autistic son's hand in an air fryer (herrrrr)
I dumped boiling water on a prison guard's head
My goofy ah friend, Jamarious Quandele Dingle tried to eat my but during Ramadhan

**Comment by paij0se** [comment]
Goofy ahh

**Comment by DeoTimeTheGithubUser** [comment]
Solved
